name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    
    - name: create library directories
      run: mkdir lib;mkdir bin
      
    - name: install dependencies
      run: sudo apt install ncurses

    - name: compile
      run: make

    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
