name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: self-hosted
   
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running on Rocky Linux"
