name: CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: echo "Running on Rocky Linux"
