name: Makefile CI

on:
  workflow_dispatch:
    branches: [ "develop0502" ]
  

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo yum install ncurses


    - name: make required dirs
      run: mkdir bin lib

    - name: build
      run: make

        
        